<a href="https://colab.research.google.com/github/avijit-avk/Assignments-LetsUpgrade-Data-Science/blob/main/Assignment_Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 1**

In [2]:
import numpy as np

print (np.arange(2,50,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


**Question 2**

In [4]:
import numpy
First_list = int(input("Enter the size of list "))
print("\n")
numList_1 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:First_list]
print("First List: ", numList_1)
print("\n")
Second_list = int(input("Enter the size of list "))
print("\n")
numList_2 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:Second_list]
print("Second List: ", numList_2)
print("\n")
Array_1 = numpy.array(numList_1)
Array_2 = numpy.array(numList_2)

print("Array1 as Numpy_Array ",Array_1)
print("Array2 as Numpy_Array ",Array_2)
print("\n")

Concatenated_array = numpy.concatenate((Array_1, Array_2), axis=0)
print("Concatenated array ", Concatenated_array)
print("\n")
Concatenated_array.sort()
print("Sorted Array ", Concatenated_array)

Enter the size of list 5


Enter the list numbers separated by space 1 2 3 4 5
First List:  [1, 2, 3, 4, 5]


Enter the size of list 7


Enter the list numbers separated by space 12 23 43
Second List:  [12, 23, 43]


Array1 as Numpy_Array  [1 2 3 4 5]
Array2 as Numpy_Array  [12 23 43]


Concatenated array  [ 1  2  3  4  5 12 23 43]


Sorted Array  [ 1  2  3  4  5 12 23 43]


**Question 3**

In [5]:
arr_2d = np.array([[1 ,2,3,1], [19, 20, 21, 22], [30,31,32,33]])
print('2D Numpy Array')
print(arr_2d)
print("\n")

# get number of rows in 2D numpy array
num_of_rows = np.size(arr_2d, 0)

# get number of columns in 2D numpy array
num_of_columns = np.size(arr_2d, 1)
print('Number of Rows : ', num_of_rows)
print('Number of Columns : ', num_of_columns)

2D Numpy Array
[[ 1  2  3  1]
 [19 20 21 22]
 [30 31 32 33]]


Number of Rows :  3
Number of Columns :  4


**Question 4**

In [6]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print('1D Numpy array:')
print(arr)
print("\n")

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print("2D Array ")
print(arr_2d)

1D Numpy array:
[10 11 12 13 14 15 16 17 18 19]


2D Array 
[[0 1 2 3 4]
 [5 6 7 8 9]]


**Question 5**

In [7]:
a = np.array([[10, 20], 
              [30, 40]]) 
  
b = np.array([[50, 60], 
              [70, 80]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]

Horizontal stacking:
 [[10 20 50 60]
 [30 40 70 80]]


**Question 6**

In [8]:
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
      
# driver code 
list1 = [11, 20, 11, 30, 42, 41] 
print("The unique values from 1st list is") 
unique(list1) 
  
# converting our list to set 
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))

The unique values from 1st list is
[11 20 30 41 42]
No of unique items in the list are: 5
